[project]
name = "oakd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "depthai>=3.10.0",
    "mediapipe>=1.0.1",
    "onnxruntime>=1.30.0",
    "opencv-python>=5.0.0.93",
]

[project.optional-dependencies]
conversion = [
    "onnx>=1.23.0",
    "tensorflow>=2.21.0",
    "tf2onnx>=1.17.0",
]
